### ISSUE TITLE
druid HoT during light ult? people are angry? success?

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/impossible-bosses-public#75] opened 2021-07-11 15:11 UTC
**Describe the bug**
lol, maybe disable this. all other HoTs aren't reflected during light ult.

OR EVERYTHING REFLECTS? EXTREME TROLL MODE??? hah, thinking about it...

**Replay & Time**

**Comment by Nowayouthere** [comment] 2022-02-20 16:38
I think any healing associeted with a "Light" aspect should definitly reflect. So works as intended?

Close this?

**Closed as completed** 2022-03-10 21:13 UTC
Labels: question
